---
- name: copy file from node1 and paste it in node2
  hosts: node1
  remote_user: ansi
  become_method: sudo
  become: true
  tasks:
    - name: copying
      fetch:
         src: /var/www/html/index.html
         dest: /tmp/
         flat: yes
    - name: transfer
      delegate_to: 192.168.1.16
      copy:
        content: "{{lookup ('file', '/tmp/index.html')}}"
        dest: /home/ramu/index.html
