---
- name: install and run
  become: true  
  hosts: all
  tasks:
    - name: install apache
      yum: 
        name: httpd
        state: present
    - name: start apache
      service:
        name: httpd
        state: started
