---
- name: gather ansible facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: install httpd service
      yum: 
        name: httpd 
        state: present
    - name: start server
      service: 
        name: httpd 
        state: started
