---
- hosts: 192.168.1.17
  remote_user: jenkins
  become_method: sudo
  become: true
  tasks:
    - copy:
        src: /var/lib/jenkins/workspace/ansible/
        dest: /var/www/html
    - service:
         name: httpd
         state: started
         enabled: yes

